# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_reg_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Register(object):
    def setupUi(self, Login_Register):
        Login_Register.setObjectName("Login_Register")
        Login_Register.resize(400, 300)
        self.title = QtWidgets.QLabel(Login_Register)
        self.title.setGeometry(QtCore.QRect(36, 10, 321, 41))
        self.title.setObjectName("title")
        self.label_login = QtWidgets.QLabel(Login_Register)
        self.label_login.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(Login_Register)
        self.label_password.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_password.setObjectName("label_password")
        self.log_line_login = QtWidgets.QLineEdit(Login_Register)
        self.log_line_login.setGeometry(QtCore.QRect(70, 110, 301, 20))
        self.log_line_login.setObjectName("log_line_login")
        self.log_line_password = QtWidgets.QLineEdit(Login_Register)
        self.log_line_password.setGeometry(QtCore.QRect(70, 160, 301, 20))
        self.log_line_password.setText("")
        self.log_line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.log_line_password.setObjectName("log_line_password")
        self.button_log = QtWidgets.QPushButton(Login_Register)
        self.button_log.setGeometry(QtCore.QRect(310, 270, 75, 23))
        self.button_log.setObjectName("button_log")
        self.button_reg = QtWidgets.QPushButton(Login_Register)
        self.button_reg.setGeometry(QtCore.QRect(200, 270, 75, 23))
        self.button_reg.setObjectName("button_reg")
        self.button_settings = QtWidgets.QPushButton(Login_Register)
        self.button_settings.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.button_settings.setObjectName("button_settings")
        self.button_forgot_password = QtWidgets.QPushButton(Login_Register)
        self.button_forgot_password.setGeometry(QtCore.QRect(110, 270, 75, 23))
        self.button_forgot_password.setObjectName("button_forgot_password")

        self.retranslateUi(Login_Register)
        QtCore.QMetaObject.connectSlotsByName(Login_Register)

    def retranslateUi(self, Login_Register):
        _translate = QtCore.QCoreApplication.translate
        Login_Register.setWindowTitle(_translate("Login_Register", "Dialog"))
        self.title.setText(_translate("Login_Register", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#00ff00;\">Your Chat</span></p></body></html>"))
        self.label_login.setText(_translate("Login_Register", "login:"))
        self.label_password.setText(_translate("Login_Register", "password:"))
        self.button_reg.setText(_translate("Login_Register", "Register"))
        self.button_log.setText(_translate("Login_Register", "Log in"))
        self.button_settings.setText(_translate("Login_Register", "Settings"))
        self.button_forgot_password.setText(_translate("Login_Register", "Forgot pass"))
