# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(400, 300)
        self.reg_line_login = QtWidgets.QLineEdit(Register)
        self.reg_line_login.setGeometry(QtCore.QRect(120, 90, 201, 20))
        self.reg_line_login.setObjectName("reg_line_login")
        self.reg_line_password = QtWidgets.QLineEdit(Register)
        self.reg_line_password.setGeometry(QtCore.QRect(120, 130, 201, 20))
        self.reg_line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reg_line_password.setObjectName("reg_line_password")
        self.reg_line_email = QtWidgets.QLineEdit(Register)
        self.reg_line_email.setGeometry(QtCore.QRect(120, 210, 201, 20))
        self.reg_line_email.setObjectName("reg_line_email")
        self.label_email = QtWidgets.QLabel(Register)
        self.label_email.setGeometry(QtCore.QRect(20, 210, 47, 13))
        self.label_email.setObjectName("label_email")
        self.label_password = QtWidgets.QLabel(Register)
        self.label_password.setGeometry(QtCore.QRect(20, 130, 51, 16))
        self.label_password.setObjectName("label_password")
        self.label_login = QtWidgets.QLabel(Register)
        self.label_login.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_login.setObjectName("label_login")
        self.title = QtWidgets.QLabel(Register)
        self.title.setGeometry(QtCore.QRect(40, 10, 321, 41))
        self.title.setObjectName("title")
        self.label_password_2 = QtWidgets.QLabel(Register)
        self.label_password_2.setGeometry(QtCore.QRect(20, 170, 91, 16))
        self.label_password_2.setObjectName("label_password_2")
        self.reg_line_password_2 = QtWidgets.QLineEdit(Register)
        self.reg_line_password_2.setGeometry(QtCore.QRect(120, 170, 201, 20))
        self.reg_line_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reg_line_password_2.setObjectName("reg_line_password_2")
        self.pushButton = QtWidgets.QPushButton(Register)
        self.pushButton.setGeometry(QtCore.QRect(290, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Register)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Dialog"))
        self.label_email.setText(_translate("Register", "email:"))
        self.label_password.setText(_translate("Register", "password:"))
        self.label_login.setText(_translate("Register", "login:"))
        self.title.setText(_translate("Register", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Registration</span></p></body></html>"))
        self.label_password_2.setText(_translate("Register", "retype password:"))
        self.pushButton.setText(_translate("Register", "Register"))
        self.pushButton_2.setText(_translate("Register", "Cancel"))
